<a href="https://colab.research.google.com/github/kigit2017/Math-Programs/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
lst = [10,20,30,40,50]

print(lst)

[10, 20, 30, 40, 50]


In [ ]:
# if i want to increase the value of each element present in list.
lst_1 = lst+10
print(lst_1)

TypeError: ignored

In [ ]:
# but if you will convert this list into array
import numpy as np
arr = np.array(lst)
arr_new = arr+10
print(arr_new)

[20 30 40 50 60]


In [ ]:
#Exercise
import numpy as np
marks=[20,30,40]
id=[0,2,4]
print(marks)
print(id)

arr1=np.array([25,56,12,85,34,75])
arr2=np.array([42,3,86,32,856])
Narr= np.random.randn(arr1.size )
arr1.size
arr1.astype(complex)
print(arr1.astype(complex))
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[:2,:2])
print("All elements in 3rd row", a[2:])
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,0],[1,1]])



[20, 30, 40]
[0, 2, 4]
[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
All elements in 3rd row [[7 8 9]]
[2 2]


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[[1,0]])
print(a[[1,0],[1,1]])
print(a[[0,1,2],[0,1,0]])

print(np.array([a[0,0],a[1,1],a[2,0]]))
#12
#34
#56
#1 4 5
print(a[[0,0],[1,1]])
#12
#12
#22

a = np.array([[4,7,1],[2,5,7],[7,1,1]])
mask = a >3
print(a[mask])
#[0,1,0],[0.1.1],[1,0,0]
a=[3,4,5,3+5j,0]
print(np.isreal(a))
print(np.iscomplex(a))

[[3 4]
 [1 2]]
[4 2]
[1 4 5]
[1 4 5]
[2 2]
[4 7 5 7 7]
[ True  True  True False  True]
[False False False  True False]


In [ ]:
coefficients =  np.array([1,-4,4])
print(coefficients)
roots = np.roots(coefficients)
print(roots)



[ 1 -4  4]
[2. 2.]
